Lysychenko/create release octopus
mindbox-moscow/github-actions pull request #15
Opened 2022-02-06 21:51 UTC by lysychenko

https://github.com/mindbox-moscow/issues-devs/issues/182

2022-02-07 09:34 UTC, clain23 requested changes
Код особо не смотрел, по логике вот что:
- все что можно автоматом - пихать автоматом
- все где есть готовые вериаблы - надо подсказку про это, чтобы не костылили
- чем проще интерфейс для того кто будет пользоваться экшеном тем лучше
- самое главное - я бы доставание релиз ноутс сделать отдельным экшеном, не мешая с обычным созданием релиза. а в композитный экшен добавил бы два экшена - доставание релиз ноутс и создание релиза, чтобы была модульность

2022-02-07 09:34 UTC, clain23 commented on octopus-create-release/action.yml
> +    description: 'Octopus Server'
Тут видимо Octopus Server Url

2022-02-07 09:34 UTC, clain23 commented on octopus-create-release/action.yml
> +    description: 'Octopus Api Key'
Наверное стоит добавить совет, типа юзай готовый вериабл

2022-02-07 09:34 UTC, clain23 commented on octopus-create-release/action.yml
> +    description: 'GitHub Token'
тут аналогично, надо юзать готовый токен

2022-02-07 09:34 UTC, clain23 commented on octopus-create-release/action.yml
> +    description: 'GitHub Repository'
нельзя ли автоматом просовывать его из того репо, откуда вызывается?

2022-02-07 09:34 UTC, clain23 commented on octopus-create-release/action.yml
> +    description: 'Current Commit'
аналогично, если можно автоматом - лучше автоматом

2022-02-08 11:22 UTC, nmlc reviewed
В целом считаю что все экшены нужно обьеденить в один - `create-release`.  Это все сильно упростит, не нужно будет в одном экшене заливать артифакт, а в другом чекать если он есть или нет.
Если нам нужно создать несколько октопус релизов в разных проэктах, считаю что это лучше делать внутри экшена, чтобы у пользователя был минимальный интерфейс.

```yaml
      - name: Create Release
        with:
          projects:
           - "project-one"
           - "project-two"
          release-number: ${{ needs.create-gh-release.outputs.release-number }}
          octopus-server: ${{ secrets.OCTOPUS_SERVER }}
          octopus-api-key: ${{ secrets.OCTOPUS_API_KEY }}
```

Минус у этого в том, что в экшенах пока нельзя ранить таски паралельно, и мы будем создавать октопус релизы последовательно. Но считаю что это ухудшение оправдано. Минимальный, чистый интерфейс эшкена > небольшое улучшение перфоманса.

Сейчас мы по сути сложность перекладываем на пользователя.

2022-02-08 11:22 UTC, nmlc commented on create-release-notes/release-gen.ps1
> +Write-Host ("Getting all commits from git tag v" + $last_release_version + " to commit sha $current_commitId.")
Тут `$last_release_version` undefined

2022-02-08 11:22 UTC, nmlc commented on octopus-create-release/action.yml
> +        path: "releasenotes.txt"
Зачем это?

2022-02-08 11:22 UTC, nmlc commented on octopus-create-release/action.yml
> +      uses: docker://octopusdeploy/octo
Helm используется в 1 репозитории из 200.
Не нравятся ифчики c модом, предлагаю их убрать и использовать `additional_params_values`

2022-02-09 07:45 UTC, merged